WIDTH = 1000
HEIGHT = 1000
FRAME_RATE_CAP = 30000
ENABLE_RENDERING = False
TIME_COEFFICIENT = 10.0
MAX_VELOCITY = 5

PLAYER_RADIUS = 20

TAG_COOLDOWN_MS = 1  # Time after being tagged when AI doesn't chase

DISCOUNT_RATE = 1
N_OF_EPISODES = 1000
POLICY_EPSILON = 0.1
MIN_EPSILON = 0
DECAY_RATE = 0.001
LEARNING_RATE = 0.001
HIDDEN_SIZE = 64

OUTPUT_DIR = "output/taggame"
MODEL_FILE = "taggame_model.pt"
POLICY_FILE = "taggame_policy.json"

PLAYER_COUNT = 2
RL_PLAYER_NAME = "Sili"